### ISSUE TITLE
[whitelist] Haunted Mansion

### ISSUE THREAD

**Issue by BrentGamesoooo** [emmVRC/emmVRC-Risky-Function-Request#10]

**Comment by Hordini** [comment]
There are quite a few uploaded worlds with similar names, and am unsure which one is correct. Would you be able to provide a link to the world on the VRChat website so I can properly locate what you're requesting?

**Comment by BrentGamesoooo** [comment]
Hello I wrote the name wrong but I will send you the right world (the name was Haunted Asylum)

Here is a launch link https://vrchat.com/home/launch?worldId=wrld_bd5fd91c-8369-438f-85d2-37ee593a5c36

**Comment by Hordini** [comment]
Denied ❌

To preserve the integrity of this game world, it will remain blocked.
