### ISSUE TITLE
I would like to use Risky functions anywhere in Vrchat With in emmVRC uidelines

### ISSUE THREAD

**Issue by ThePortableSpeaker** [emmVRC/emmVRC-Risky-Function-Request#101]
I would like to be able to use RISKY FUNCTIONS in of any world, it would be fun to mess around with my friends in private games to have a good time. I will be using them in public lobbies as well but as long as all players are ok with me just messing around and not to be unfair. If players are displeased with me using risky functions I will turn so mods off and play normally. If you end up declining my request I will not try again and live with what I have. have a nice day
                                                                                                  Thank you for your time
                                                                                                                                Yours truly ThePortableSpeaker

**Comment by BLANKE1** [comment]
[Please read what this repo is for](https://github.com/emmVRC/emmVRC-Risky-Function-Request#emmvrc-risky-function-request) this isn't a repo to ask "Pretty please may I have wisky funcwins I pwinky pwomise I won't be bad I swher I won't hurt anybodies". Read the other issues to get an example for what this repo is exactly for.

**Comment by rakosi2** [comment]
The only person that is allowed to use risky in worlds tagged as `game` or `club` is the world creator/uploader. Not even emmVRC staff have special exceptions to that.
