### ISSUE TITLE
Risky function request

### ISSUE THREAD

**Issue by SamHecmxila** [emmVRC/emmVRC-Risky-Function-Request#102]
Perhaps risky function update is a better title? I found a world in VRC with the best flight system I've ever seen, the world's name is "Afterwords island" the flight system works as: you grab your ear and then a stick appears in your hand if you make a fist again then the stick will freeze and you'll fly in the direction you move your hand. I got the package for it here on github but was disappointed to find out that it was a "worlds only" package. I would absolutely love to see that flight system added to emm. Thanks for hearing me out! Have fun! Stay safe! And thank you guys for all your hard work on emm!

**Comment by Janni9009** [comment]
You'll want to submit that as a [Feature Request](https://github.com/emmVRC/emmVRC-Public/issues) instead. This repo is purely for white-/blacklisting worlds.
