### ISSUE TITLE
can we a in im BOMBERio

### ISSUE THREAD

**Issue by blueishv** [emmVRC/emmVRC-Risky-Function-Request#108]
can we plz have it that game i like playing it with my friends and have laff

**Comment by BLANKE1** [comment]
The world is clearly a game world and [you didn't format your title correctly](https://github.com/emmVRC/emmVRC-Risky-Function-Request#emmvrc-risky-function-request), please note that [VRChat's TOS only allows people over the age of 13](https://hello.vrchat.com/legal). Risky functions are blocked in game/club worlds to prevent cheating or invasion of privacy, there is 0 exceptions to it. There is no way of moderation a public mod to give people this ability.
