### ISSUE TITLE
[WHITELIST] <Dream Waves>

### ISSUE THREAD

**Issue by batpoison** [emmVRC/emmVRC-Risky-Function-Request#114]
**World ID that you want to whitelist.**
wrld_860bdea8-0499-4c16-8170-5683a3a3ab8a

**Have you read README.md?**
yes

**Are you the world creator?**
no

**Why should this world be whitelist?**
Chill hangout world... It has a vip lounge that does not render unless you have world permission to enter it.

**Additional context**
I use emm with immobilizer to simulate fbt when im hanging out with friends and this is one of our new fav worlds and risky funcs are disabled.

**Comment by BenjaminZehowlt** [comment]
Risky functions were explicitly disabled by the world creator & has a VIP room as you mentioned
