### ISSUE TITLE
[WHITELIST] The Backrooms V5․8․5

### ISSUE THREAD

**Issue by honeypie3301** [emmVRC/emmVRC-Risky-Function-Request#115]
### World ID that you want to whitelist.

wrld_a2279029-c555-4fed-945f-dde72e8fac0b&instanceId

### I have read README.md

- [X] Yes

### Are you the world creator?

No

### Why should this world be whitelist?

just having a little bit of difficulty to beat the game that is all.

**Comment by BenjaminZehowlt** [comment]
Game worlds won't be whitelisted.
