### ISSUE TITLE
[WHITELIST] Backrooms VRC

### ISSUE THREAD

**Issue by mr2meowsYT** [emmVRC/emmVRC-Risky-Function-Request#118]
### World ID that you want to whitelist.

wrld_5fcc23cf-bf0b-40d2-b678-31f906b13afd

### I have read README.md

- [X] Yes

### Are you the world creator?

No

### Why should this world be whitelist?

the world is just run around in hallways until someone crashes the entire server
idk why its tagged as game

**Comment by averagemgrrplayer** [comment]
dawg just play a private room and try not to die

**Comment by rakosi2** [comment]
There is already ticket #106 open
