### ISSUE TITLE
[Blacklist] VirtualFurence Furry Convention Project

### ISSUE THREAD

**Issue by Reimajo** [emmVRC/emmVRC-Risky-Function-Request#12]
Please blacklist my public world. It includes private rooms / areas that should not be accessible to other players by default and risky functions also mess up the world logic.
https://vrchat.com/home/world/wrld_b155ff30-0bbf-486c-afc5-e7a05145387b
Thanks in advance :)

**Comment by Hordini** [comment]
Accepted ✔️

I was unable to find any private rooms / areas, however we always comply with the world creator's wishes.
