### ISSUE TITLE
[WHITELIST] Survival The Shrek The Killer

### ISSUE THREAD

**Issue by averagemgrrplayer** [emmVRC/emmVRC-Risky-Function-Request#120]
### World ID that you want to whitelist.

wrld_fd98f85c-164d-4dae-8bfe-b65f2897266f

### I have read README.md

- [X] Yes

### Are you the world creator?

No

### Why should this world be whitelist?

All it's just a game that (i assume) was made as a joke, so I don't think anyone would care (unless if the creator does). And also, It would probably be funny for people to see somebody fly past all of the Shreks. And it's not really a race to the finish either.

**Comment by averagemgrrplayer** [comment]
i forgot to add the world name sorry

**Comment by rakosi2** [comment]
I know Hens and they told me they tagged the world as `game` specifically to disable emmVRC's risky functions.
