### ISSUE TITLE
[WHITELIST] The Buzz Games

### ISSUE THREAD

**Issue by NomenSquad** [emmVRC/emmVRC-Risky-Function-Request#122]
### World ID that you want to whitelist.

wrld_859b00d5-c535-42dd-aee8-da0178bcc15a

### I have read README.md

- [X] Yes

### Are you the world creator?

Yes

### Why should this world be whitelist?

I would like this world whitelisted because the idea of this world I created was suppose to use flight. This was meant to be a kind of RPG game were you fly everywhere while fighting in the arena like Dragon Ball Z Cell Games Saga.

### Additional context

![Screenshot 2022-07-05 203813](https://user-images.githubusercontent.com/108778630/177462993-9fcae3e2-56e7-4c5c-a593-495ccb5e7f4d.png)
I sending also a screen shot for more proof that I'm the owner.

**Comment by BenjaminZehowlt** [comment]
If you're the uploader of the world please use `UniversalRiskyFuncEnable` in the root of the world.
