### ISSUE TITLE
[WHITELIST] Angel's Share (Genshin Impact)

### ISSUE THREAD

**Issue by thatmikerotch** [emmVRC/emmVRC-Risky-Function-Request#128]
### World ID that you want to whitelist.

wrld_e303374f-3f3d-4489-ba46-32729e1e47de

### I have read README.md

- [X] Yes

### Are you the world creator?

Yes

### Why should this world be whitelist?

I use it primarily and wouldn't mind if it's used in this world that I created. :)

### Additional context

Also thank you for creating a useful/wonderful mod. been using it for three years <3

**Comment by BenjaminZehowlt** [comment]
Please use a gameobject named `UniversalRiskyFuncEnable` in the root of the world.
