### ISSUE TITLE
[WHITELIST] Just B Club

### ISSUE THREAD

**Issue by jakkuedits** [emmVRC/emmVRC-Risky-Function-Request#13]
There are no private rooms/games in this world so I see no reason why you shouldn't be able to use Speed/Waypoints to get around faster.

**Comment by Provini** [comment]
This may remain as is as private rooms are planned for the world.
![image](https://user-images.githubusercontent.com/71570801/102107758-10efb880-3e00-11eb-99d0-36ce135f11f3.png)

**Comment by Hordini** [comment]
Denied ❌

As indicated by the image above, as well as elevator buttons for future expansions that include private rooms, Risky Functions in this world will remain disabled.
