### ISSUE TITLE
[WHITELIST] DRINKING NIGHT

### ISSUE THREAD

**Issue by TrueSleepy** [emmVRC/emmVRC-Risky-Function-Request#18]
**** Even tho its a game world its more of a social to drink and hang out and flying alows us with smaller avatars to be able to see on the table

**Comment by RiskiVR** [comment]
Drinking night is also tagged as a club world, as it has private rooms. So to protect the privacy of others, risky functions won't be allowed so people can't teleport to those rooms.

**Comment by Hordini** [comment]
Denied ❌

Due to the inclusion of private rooms, this world will not be whitelisted.
