### ISSUE TITLE
[BLACKLIST] The Snooze's Scary Maze 5

### ISSUE THREAD

**Issue by StryderNyu** [emmVRC/emmVRC-Risky-Function-Request#20]
Noclipping or using speed through the maze is becoming out of hand with cheating and users submitting completion pictures for the wall of fame and it honestly takes out the challenge of beating the maze 
Using noclip or speed just makes you out run the chasers or sentries. 

We'd like to have a photo wall that's not trying to be filled with cheaters while they brag that they beat the maze by cheating but making it sound legit.

**Comment by Hordini** [comment]
Accepted ✔️
