### ISSUE TITLE
[BLACKLIST] Club Astro

### ISSUE THREAD

**Issue by techno-warrior** [emmVRC/emmVRC-Risky-Function-Request#24]
Please blacklist my world Club Astro (https://vrchat.com/home/world/wrld_bd3153ec-a990-4652-ad37-5736627390f6) from risky functions as it contains private staff/VIP areas as well as entry control during events that noclip can mess with and bypass

WiseWolf

**Comment by rakosi2** [comment]
If you tag your world as a game or club, emmVRC will automatically blacklist your world. Otherwise it may take several days to go through the process.

**Comment by techno-warrior** [comment]
Thanks for that, didnt try it since it went public and I added the club tag
