### ISSUE TITLE
Risky Functions Request

### ISSUE THREAD

**Issue by johndoehg** [emmVRC/emmVRC-Risky-Function-Request#26]
Hello! I would love to get risky functions since I will be responsible with them. I spend a lot of time on VRChat and it helps me with my anxiety. The reason why im asking for these permissions is because I would like to see what types of avatars there is and just explore the permissions overall. Thank you for reading!

**Comment by RiskiVR** [comment]
Risky Function are already free to use, just enable them in emmVRC Settings. This page is for requesting a specific world to be whitelisted or blacklisted from Risky Functions.

**Comment by johndoehg** [comment]
oh im sorry.
