### ISSUE TITLE
[WHITELIST] ZombieSlayer2k7 e9a3

### ISSUE THREAD

**Issue by ZombieSlayer2k7** [emmVRC/emmVRC-Risky-Function-Request#27]

**Comment by rakosi2** [comment]
You don't need to whitelist yourself. All you need to do is enable risky features in emmVRC's settings. By default, Risky Functions are not allowed to be used in worlds tagged with Game or Club to prevent cheating or invasion of privacy. This site is for adding worlds to whitelist or blacklist.
