### ISSUE TITLE
Whitelist Paradise Untouched

### ISSUE THREAD

**Issue by Rio-Grande** [emmVRC/emmVRC-Risky-Function-Request#3]
Hello,

I am the creator of this world and I would like it to be re-whitelisted. I dont know who requested it to be blacklisted but i can guarantee there is no locking doors or games to cheat at that would necessitate it getting black listed. If possible I would also like to know who requested the black list to begin with. 

thank you for your time
Rio.

**Comment by Hordini** [comment]
Approved ✅

Risky Functions were restricted in the world due to the Club tag being present
