### ISSUE TITLE
[WHITELIST] Zixha's apartment

### ISSUE THREAD

**Issue by forever-and-a-day** [emmVRC/emmVRC-Risky-Function-Request#31]
The only games in this world are spin the wheel, king's game, 8ball, beer pong, and never have I ever. There are no private rooms. Risky functions would be useful for teleporting to friends. Thanks! :) 
Link: https://vrchat.com/home/launch?worldId=wrld_383c3fd1-ef79-489f-a971-a025b53aadf3

**Comment by Hordini** [comment]
Accepted ✔️
