### ISSUE TITLE
[WHITELIST] Japan Street 0.140

### ISSUE THREAD

**Issue by explodingkittns** [emmVRC/emmVRC-Risky-Function-Request#32]
World ID: wrld_02cb84c8-446a-484b-b52b-2c1777e55f8d

This world is marked as "game," but it is not a game world. It has a 2048 game in it on a wall panel, but that's tucked away in only one of the buildings. There are no lockable private rooms that I have found. This would would greatly benefit from risky functions due to its massive size.

**Comment by Hordini** [comment]
Accepted ✔️
