### ISSUE TITLE
[BLACKLIST] Midnight Munchies Theater

### ISSUE THREAD

**Issue by markthomas007** [emmVRC/emmVRC-Risky-Function-Request#34]
Please blacklist the Midnight Munchies Theater. We have a private dj area that we only want certain people to use and will soon have a new moderation tool in the world that would not work if the person has noclip.
[Midnight Munchies Theater](https://vrchat.com/home/world/wrld_1b0090ad-9c39-4b6a-bfdf-9c53bfd5988b)
Oh and yes its not uploaded by me but i helped with the udon of the world and im credited the world.

**Comment by Hordini** [comment]
Accepted ✔️
