### ISSUE TITLE
[BLACKLIST] Xzenith's Home

### ISSUE THREAD

**Issue by XzenithVR** [emmVRC/emmVRC-Risky-Function-Request#36]
I wanted to have this world blacklisted because I plan to add lockable rooms in the future along with a couple of secret rooms.

**Comment by rakosi2** [comment]
The easiest way for a world dev to disallow emmVRC to work in a world is by adding the tags 'game' or 'club' or by adding a root GameObject called 'eVRCRiskFuncDisable'. Otherwise, you will need to wait a few days for your world to go through the approval process.

**Comment by XzenithVR** [comment]
so all i need to do is add a cube called "eVRCRiskFuncDisable"?

**Comment by XzenithVR** [comment]
nevermind i got it
