### ISSUE TITLE
Sitting on heads support

### ISSUE THREAD

**Issue by Proshi** [emmVRC/emmVRC-Risky-Function-Request#39]
So I just moved from a Client that allowed me to sit on others' head and I feel like it's a great addition to have. Namely for use in Friend/ private lobbies. Probs would be beat to have it blacklisted from stuff like Among us and Murder. I think it was called follow from what it was on there. Since it's not malicious I feel like it would be a great fit for here.

**Comment by KortyBoi** [comment]
Regardless of it being a game world or not, this can be considered a "malicious" feature and will not be implemented into emmVRC.
I simple example of how this can be malicious is as follows:
This can be viewed as harassment if the other user does not want someone sitting on / attached to their head.
