### ISSUE TITLE
Blacklist a game world

### ISSUE THREAD

**Issue by GalacticAJanya** [emmVRC/emmVRC-Risky-Function-Request#4]
Request: Blacklist for risky functions,
Name of world: Maniac's Mansion (author: spazkoga),
Reason: It has death system and active game with enemies to reach the goal, cheating can easily get one advantage through enemy areas in race to finish and bybass death room suppose to force you reset instance.

**Comment by Hordini** [comment]
Denied ❌

Using Risky Functions in this world does not negatively effect other players, only the user's own experience.
