### ISSUE TITLE
STRIPCLUB ＂SWAG＂

### ISSUE THREAD

**Issue by louis20011207** [emmVRC/emmVRC-Risky-Function-Request#43]
please turn off the abilities on this map Fly, Noclip, Jump, Waypoints, Speed, and Teleporting.

**Comment by rakosi2** [comment]
World's that are tag as 'game' or 'club' or have an empty root gameobject called 'eVRCRiskFuncDisable' will have emmVRC risky automatically disabled. Otherwise please wait until a moderator is available to check the world.

**Comment by KortyBoi** [comment]
The world in question contains multiple private rooms. Unless the creator adds the empty game object `eVRCRiskFuncDisable` to allow risky functions, we will not be allowing risky functions in the world.

**Comment by rakosi2** [comment]
`eVRCRiskFuncDisable` to disallow risky, and `eVRCRiskFuncEnable` to allow risky.

**Comment by Hordini** [comment]
This world has the Club tag, so a Blacklist is not necessary. If this changes at a later date, and a Blacklist is applicable, please let us know.
