### ISSUE TITLE
[BLACKLIST] UDON Rubber Dragon Labs

### ISSUE THREAD

**Issue by Earthstorm** [emmVRC/emmVRC-Risky-Function-Request#46]
I own the world and it contains private rooms.

**Comment by N4IL** [comment]
Forgot where it is stated, but for future reference, there's a way to disable them before uploading in unity with a game object or something.

**Comment by rakosi2** [comment]
Setting the world tag as 'game' or 'club' or create a root GameObject called 'eVRCRiskFuncDisable' will disable risky features.

**Comment by Hordini** [comment]
The Club tag has been added to this world, so a Blacklist is not needed. If you plan on removing the tag, and would still like to request a Blacklist, please let us know.
