### ISSUE TITLE
[Whitelist] Hazbin Hotel For QUEST

### ISSUE THREAD

**Issue by EmberDrake** [emmVRC/emmVRC-Risky-Function-Request#47]
This world is an abandoned project. Has no PVP nor Private Rooms. and only recently gotten the "Game" tag from the fact it has a beat saber clone and drinking games as a toggle in one of the rooms. It's a social hangout mostly. There is a large open city that desktop users cannot get to certain parts without EMM or Noclip. essentially.

**Comment by Hordini** [comment]
Accepted ✔️
