### ISSUE TITLE
[WHITELIST] or [BLACKLIST] World Name

### ISSUE THREAD

**Issue by vallerion19** [emmVRC/emmVRC-Risky-Function-Request#48]
I want to have my avatar back and I want to touch other collider if u can just give me again EMM VRC .
My name in the game is ~vallerion~
I am on your discord ( my name on discord is: vallerion)

**Comment by loukylor** [comment]
That's not what this is for. It's a request to blacklist or whitelist (allow or not allow) risky functions in worlds. We do not have this system for individual users. 

That being said, risky functions are not required for global dynamic bones (touching other people), and there is likely another issue. I can continue helping in the discord.

**Comment by vallerion19** [comment]
I just want emm vrc.. How I can get it?

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by loukylor** [comment]
There is a how-to in the discord.
