### ISSUE TITLE
[Whitelist] London Solitude

### ISSUE THREAD

**Issue by signal-org** [emmVRC/emmVRC-Risky-Function-Request#49]
The world recently got the game tag because it has pool. You can't use risky functions to cheat at pool. There are also no private rooms in this world.

**Comment by sasshunter** [comment]
Weird, this was the subject of #33 as well, and the world ID hasn't changed either.

**Comment by rakosi2** [comment]
That is possible because emmVRC checks if a world is white or blacklisted through our servers and they were down yesterday. As sasshunter said, London Solitude is already whitelisted and is working now.
