### ISSUE TITLE
[BLACKLIST] SAIYAN ARMY- KAME HOUSE 

### ISSUE THREAD

**Issue by nickmensch** [emmVRC/emmVRC-Risky-Function-Request#51]
I made this world for a dragon ball z group but a lot of members are noclipping to areas that a reserved for the admins of our group. I want to disable all risky functions on this world. Thank you. Here is a link to the world to make sure you get the right one 
https://vrchat.com/home/launch?worldId=wrld_11f3457f-da08-4817-99d2-416b1c9db6f3

**Comment by Hordini** [comment]
Accepted ✔️
