### ISSUE TITLE
[BLACKLIST] Spaceship Hangout

### ISSUE THREAD

**Issue by JackCapel2314** [emmVRC/emmVRC-Risky-Function-Request#52]
https://vrchat.com/home/launch?worldId=wrld_0a6542e0-2bab-435a-9d53-f8f1f5aa4b4d On behalf of one of my friends who doesn’t use emmvrc, he wanted his world to have no risky functions since there are lockable rooms which he doesn’t want invading once locked. Thanks 😊

**Comment by loukylor** [comment]
You can easily do this by adding a the "game" or "club" tag to the world. You can also add a gameobject with the name `eVRCRiskFuncDisable` to the root gameobject to disallow risky functions.

**Comment by Hordini** [comment]
Accepted ✔️
