### ISSUE TITLE
[Whitelist] SPIRITS OF THE SEA 海の幽霊

### ISSUE THREAD

**Issue by Rothuith** [emmVRC/emmVRC-Risky-Function-Request#56]
Has game tags due to multiple games inside the house, usually, these are private worlds. Games included are stuff like 8 Ball (Pool Tables), dice tossing and etc.

**Comment by Hordini** [comment]
It would seem that the Game tag was removed from this world. Feel free to contact us again if this changes in the future, and a whitelist is still applicable.
