### ISSUE TITLE
[WHITELIST] VRCDOOM

### ISSUE THREAD

**Issue by BatPisz** [emmVRC/emmVRC-Risky-Function-Request#59]
https://vrchat.com/home/launch?worldId=wrld_1256060a-6fe6-4b5f-b6f6-619c99ddeb1c
The game's practically dead in playercount, default player speed is pretty unbearably slow (especially for completing in desktop as you only have one hand), and I've just always wanted to freely explore the map. I'd find it to be very enjoyable if it were whitelisted.

**Comment by Skard-Hrothgarsson** [comment]
plus, last i checked, it's not pvp.

**Comment by Hordini** [comment]
Accepted ✔️
