### ISSUE TITLE
[Whitelist] Samovar

### ISSUE THREAD

**Issue by v2elite** [emmVRC/emmVRC-Risky-Function-Request#6]
Hi, please whitelist my world for RF. Thank you!

https://vrchat.com/home/launch?worldId=wrld_0b15f622-81f3-4271-9e46-237ab5549401

**Comment by Hordini** [comment]
Risky Functions are already allowed to be used in this world. Ensure that You have Risky Functions enabled in emmVRC Functions > Settings.
