### ISSUE TITLE
[WHITELIST] City 17 | VRCValve

### ISSUE THREAD

**Issue by DonaldDump4** [emmVRC/emmVRC-Risky-Function-Request#60]
This world is designed for RP, and has a game tag, however, the only "Game" in this world is a pool table in one of the apartments, and I believe that enabling risky functions will not degrade an RP experience more than someone could without emm. There are also no locked doors, and someone without a client could easily access any location in the world.

**Comment by MintLily** [comment]
The creator has specifically added multiple ways, and multiple physical signs in the world, saying client use is strictly prohibited. We will not be adding this to our whitelist. If the creator wants to reverse this, they can say so otherwise.
