### ISSUE TITLE
[BLACKLIST] Moon's Gambling Pit

### ISSUE THREAD

**Issue by LethalMoon** [emmVRC/emmVRC-Risky-Function-Request#61]
The reason i would like to blacklist this world is because i catch client users throwing pickups outside the world where no one can get them and no clipping to the staff room

**Comment by loukylor** [comment]
If this is your world, simply add a gameobject in the root called `eVRCRiskFuncDisable`

**Comment by Hordini** [comment]
Accepted ✔️
