### ISSUE TITLE
[WHITELIST] Red Carpet Theatre

### ISSUE THREAD

**Issue by wifiplz** [emmVRC/emmVRC-Risky-Function-Request#66]
I made this. I'm not sure if it allows risky features currently as I don't use Emm. 
It will later have the games tag so I would like to preemptively have it whitelisted.

**Comment by Afootpluto** [comment]
Make a blank root gameobject called eVRCRiskFuncEnable and it will allow risky functions.

**Comment by MintLily** [comment]
This was on the patch notes for emmVRC v2.7.0
> • World creators can now choose to allow or disallow Risky Functions via a root GameObject. eVRCRiskFuncDisable to disallow them, and eVRCRiskFuncEnable to allow them.
