### ISSUE TITLE
Force Cloning (wholesome edition)

### ISSUE THREAD

**Issue by LGBTQLMNOP** [emmVRC/emmVRC-Risky-Function-Request#67]
for real yall should add force cloning for public avatars only for trusted and patreon users could have access to this feature. It would save a bunch of time trying to go to another world to find an avatar then coming back just to use it for a couple of hours if not minutes and it would definitely help emmvrc reach its funding goal on god respectfully.

**Comment by Hordini** [comment]
emmVRC will not be adding any paid features exclusive to our supporters, nor any that break our Blacklisted Features list: https://github.com/emmVRC/emmVRC-Public/issues/7.
I recommend asking the user if they could enable cloning if you're interested in doing so.

This repo is meant for requesting the addition or removal of Risky Functions checks in worlds, not feature requested. Please use the correct repo next time: https://github.com/emmVRC/emmVRC-Public

**Comment by LGBTQLMNOP** [comment]
alright my bad Houdini didn't mean to rumble your feathers ill make sure to submit a request when im not half asleep
