### ISSUE TITLE
World to add

### ISSUE THREAD

**Issue by Voiddom** [emmVRC/emmVRC-Risky-Function-Request#69]
Murder 4 for jumping only

**Comment by loukylor** [comment]
Murder 4 doesnt not require jumping unless you are miniscule, in which case you should switch into a larger avatar.

Ignoring the problem would bring up another issue, that the way emm is set up, you cannot enable certain risky functions, only none or all of then.

**Comment by Voiddom** [comment]
alrighty thanks
