### ISSUE TITLE
[Whitelist] Serenity Cove

### ISSUE THREAD

**Issue by ZappiestCash** [emmVRC/emmVRC-Risky-Function-Request#71]
I am the creator of the world, Serenity Cove, and I would like to request it gets whitelisted. There are no completely private areas or any games that a player could possibly use emmVRC to cheat in. Thank you!

**Comment by BLANKE1** [comment]
You can add a empty object to the root of the world named eVRCRiskFuncEnable to basically force it

**Comment by loukylor** [comment]
If you're afraid of putting something emm specific in your world, it might be reassuring for you to know that Just B-Club uses the gameobject to not allow emm functions so you won't get banned for it.

**Comment by rakosi2** [comment]
Seeing as Risky is allowed, most likely by eVRCRiskFuncEnable, I will now close this issue
