### ISSUE TITLE
[Blacklist] Japan Street 0․199 

### ISSUE THREAD

**Issue by SplitScream** [emmVRC/emmVRC-Risky-Function-Request#73]
World ID: wrld_02cb84c8-446a-484b-b52b-2c1777e55f8d

Japan Street has the "Game" tag enabled purposely to disable Risky Functions by owner. Please Reverse the previous request to whitelist.

![Owner Request](https://user-images.githubusercontent.com/43389130/131247211-eb54cd44-6ff3-44e8-ba78-b564dbdd2bae.PNG)

**Comment by loukylor** [comment]
If the iwner wishes for the game to have risky functions blocked then we will not reverse this.

**Comment by rakosi2** [comment]
They were talking about #32 and asking for us to undo the whitelist

**Comment by loukylor** [comment]
Ah, my bad.

**Comment by SplitScream** [comment]
> If the owner wishes for the game to have risky functions blocked then we will not reverse this.

Another Player request it to be whitelisted
The Owner wants it Blacklisted

We wanted the Whitelist #32  undone

**Comment by rakosi2** [comment]
I have verified that Risky functions are no longer allowed in Japan Street 0.199 Sorry for the inconvenience we may have caused with #32

**Comment by BLANKE1** [comment]
Btw if they want it blacklisted they could of put an empty object named eVRCRiskFuncDisable in their scene root

**Comment by SplitScream** [comment]
> Btw if they want it blacklisted they could of put an empty object named eVRCRiskFuncDisable in their scene root
I recommend this being added to the readme, we cannot find this anywhere
