### ISSUE TITLE
Allow use of Risky Functions in private instances

### ISSUE THREAD

**Issue by flarn2006** [emmVRC/emmVRC-Risky-Function-Request#74]
I think if you're in an Invite Only or Friends Only instance, you should be able to use Risky Functions no matter what. This will ensure people can use the functions as they please so long as they aren't affecting other players that aren't okay with it.

**Comment by BLANKE1** [comment]
That's essentially a pinky promise. People hold events in Private instances so I don't think it'll work like that.

**Comment by flarn2006** [comment]
Perhaps the owner of the lobby could enable it for themselves and other players?

**Comment by loukylor** [comment]
> Perhaps the person who created the instance could enable it for themselves and other players?

Along with the issue of that needing a almost complete rewrite of the emm backend, the instance creator may not be there, and relying on the instance master would be just as unreliable. Both the instance master and creator could be malicious.

> If nothing else, it should at least always allow it while you're the only person in the instance, as in that case there's nobody else you'd be affecting.

Some game worlds rely on leaderboard systems, which could still be cheated on in worlds with only you in the instance.
