### ISSUE TITLE
[WHITELIST] MOVIE & CHILL  (NEW & UPDATED)

### ISSUE THREAD

**Issue by C3-Inferno** [emmVRC/emmVRC-Risky-Function-Request#77]
It has the Game tag but the only featured games are Chess, Darts, Pool. non ow witch are influenced by the risky functions. the world even has its own player standing level changer for the game space. but it would be nice to use the risky functions where the floor level is not raised. or to just walk faster or fly. There is no real Game that is manipulated by the risky functions.

**Comment by rakosi2** [comment]
emmVRC Risky is now allowed in the world. Avoid using Risky in public instances as reports can lead to bans.
