### ISSUE TITLE
[WHITELIST] Hiccups

### ISSUE THREAD

**Issue by x3Syntax** [emmVRC/emmVRC-Risky-Function-Request#80]
Reason for the request: Its my World which is more likely used for playing card games and havin fun with friends. If people can fly it wouldnt change the game feeling of anybody because there isnt features which challange players against each others. 

Basically its just a dance / drink / table games world. 

Best regrets,
x3Syntax

**Comment by rakosi2** [comment]
Was Whitelisted via GameObject.
