### ISSUE TITLE
World needs EMM Disabled

### ISSUE THREAD

**Issue by GAMR1O1** [emmVRC/emmVRC-Risky-Function-Request#85]
I was visiting a world when i realized that there was a locked door mechanic attached. Meaning that the world owner wanted privacy included, and with the EMM functions, it would not be as such. Therefore, I think it would be right to disable EMM for this world.
https://vrchat.com/home/launch?worldId=wrld_860bdea8-0499-4c16-8170-5683a3a3ab8a&instanceId=14464~private(usr_c0093804-6747-4b8f-9866-b82e957b8c12)~region(us)~nonce(8db59726-3507-4c93-ab75-aed949f282ef
![privacy](https://user-images.githubusercontent.com/95512516/144693855-81b74e81-6bf4-40d8-91b1-3217ebdab953.PNG)

**Comment by thetrueyoshifan** [comment]
Accepted ✔️
