### ISSUE TITLE
[Blacklist]

### ISSUE THREAD

**Issue by ShakesPearre** [emmVRC/emmVRC-Risky-Function-Request#86]
Please blacklist my public world. It's a private room / area that should not be accessible to other players by default and risky functions also mess up the world logic.
https://vrchat.com/home/world/wrld_4321dc41-ea7e-4a24-9236-0bf5015aeb3d
Thanks in advance :)
![Screenshot_31](https://user-images.githubusercontent.com/45083008/145497068-fe8f353e-0fc0-499f-a474-aac1a6d6cf65.png)

**Comment by BLANKE1** [comment]
Add eVRCRiskFuncDisable as a root gameobject, or put the club tag on the world

**Comment by ShakesPearre** [comment]
what do you mean by the root gameobject and where could i find it?

**Comment by BLANKE1** [comment]
just add a gameobject to the root of the scene named eVRCRiskFuncDisable

**Comment by ShakesPearre** [comment]
ohh that's it? thanks

**Comment by rakosi2** [comment]
Blacklisted via GameObject
