### ISSUE TITLE
emmvrc

### ISSUE THREAD

**Issue by Harveylol** [emmVRC/emmVRC-Risky-Function-Request#89]
it says not connected to the emmvrcNetwork dont know what to do

**Comment by rakosi2** [comment]
This is not the place to ask for support. a better place to ask is in our discord [discord.gg/emmvrc](https://discord.gg/emmvrc)
To connect, you just need to type in a pin into the ![Alert Button](https://cdn.discordapp.com/emojis/757905959736705024.png?size=24) button
