### ISSUE TITLE
whitelist-MURDER MYSTERY 4

### ISSUE THREAD

**Issue by gorrillaman1234567** [emmVRC/emmVRC-Risky-Function-Request#93]
WELL ONLY FOR PRIVATE OR FRIENDS+ AND FRIENDS LOBBY HOPE THATS REASONABLE ALSO SORRY FOR CAPS

**Comment by BLANKE1** [comment]
That still can be abused for things like party nights, also risky functions will stay in effect no matter what instance type.

**Comment by rakosi2** [comment]
Duplicate of #41 #44 #65 and #91
